language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit

matrix:
  allow_failures:
    - php: '7.0'
    - php: hhvm
    - php: nightly
  fast_finish: true

notifications:
    on_success: never
    on_failure: always